"""Turn results into ``results.md``. Nothing in this repository is hand-typed.

Rule (roadmap 0.5): if a number appears in the README or in ``results.md``, a
script put it there, and the provenance block above it says which script, at
which commit, over which seeds, on how many samples. Hand-typing one number is
how a repository ends up defending a claim nobody can reproduce.
"""

import platform
import re
import subprocess
from datetime import datetime, timezone

import numpy as np

RESULTS_PATH = "results.md"

_HEADER = """# Results

**This file is generated. Do not edit it by hand.**

Regenerate with:

```bash
python bench.py     # baseline table
python ablate.py    # mechanism ablation table
```

Each section below records the commit, seed list and sample counts that produced
it. Decision criteria for these numbers were fixed in advance in
[`PREREGISTRATION.md`](PREREGISTRATION.md).
"""


def git_describe():
    def run(*args):
        try:
            return subprocess.run(args, capture_output=True, text=True,
                                  timeout=10).stdout.strip()
        except (OSError, subprocess.SubprocessError):
            return ""

    commit = run("git", "rev-parse", "--short", "HEAD") or "unknown"
    dirty = bool(run("git", "status", "--porcelain"))
    return commit + (" (working tree dirty)" if dirty else "")


def provenance(script, seeds, n_train, n_test, extra=None):
    lines = [
        f"- **Generated by:** `{script}`",
        f"- **Commit:** `{git_describe()}`",
        f"- **When:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        f"- **Seeds:** {list(seeds)} ({len(seeds)} runs, reported as mean ± sample std)",
        f"- **Samples:** {n_train:,} train / {n_test:,} test",
        f"- **Environment:** Python {platform.python_version()}, NumPy {np.__version__}",
    ]
    for item in extra or []:
        lines.append(f"- {item}")
    return "\n".join(lines)


def fmt_mean_std(values, places=2):
    values = np.asarray([v for v in values if not np.isnan(v)], dtype=float)
    if values.size == 0:
        return "n/a"
    if values.size == 1:
        return f"{values[0]:.{places}f}"
    return f"{values.mean():.{places}f} ± {values.std(ddof=1):.{places}f}"


def paired_ci95(deltas):
    """Mean and 95% t-interval of paired per-seed differences.

    This is the statistic ``PREREGISTRATION.md`` section 3 commits to: a
    mechanism is dead when this interval contains zero.
    """
    deltas = np.asarray(deltas, dtype=float)
    n = deltas.size
    mean = float(deltas.mean())
    if n < 2:
        return mean, float("nan"), float("nan")
    stderr = float(deltas.std(ddof=1) / np.sqrt(n))
    # Two-sided 95% t critical values for small n; falls back to 1.96.
    t_table = {2: 12.706, 3: 4.303, 4: 3.182, 5: 2.776, 6: 2.571, 7: 2.447,
               8: 2.365, 9: 2.306, 10: 2.262, 11: 2.228, 12: 2.201}
    t = t_table.get(n, 1.96)
    half = t * stderr
    return mean, mean - half, mean + half


def markdown_table(headers, rows, align=None):
    rows = [[str(cell) for cell in row] for row in rows]
    widths = [max(len(str(headers[i])), *(len(r[i]) for r in rows)) if rows
              else len(str(headers[i])) for i in range(len(headers))]
    align = align or ["left"] + ["right"] * (len(headers) - 1)

    def line(cells):
        return "| " + " | ".join(
            c.ljust(widths[i]) if align[i] == "left" else c.rjust(widths[i])
            for i, c in enumerate(cells)
        ) + " |"

    sep = "| " + " | ".join(
        ("-" * widths[i]) if align[i] == "left" else ("-" * (widths[i] - 1) + ":")
        for i in range(len(headers))
    ) + " |"
    return "\n".join([line([str(h) for h in headers]), sep] + [line(r) for r in rows])


def write_section(name, body, path=RESULTS_PATH):
    """Replace (or append) a delimited section of results.md."""
    begin, end = f"<!-- BEGIN {name} -->", f"<!-- END {name} -->"
    block = f"{begin}\n{body.strip()}\n{end}"

    try:
        with open(path, "r", encoding="utf-8") as handle:
            current = handle.read()
    except FileNotFoundError:
        current = _HEADER

    if not current.lstrip().startswith("# Results"):
        current = _HEADER + "\n" + current

    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    if pattern.search(current):
        updated = pattern.sub(lambda _: block, current)
    else:
        updated = current.rstrip() + "\n\n" + block + "\n"

    with open(path, "w", encoding="utf-8") as handle:
        handle.write(updated.rstrip() + "\n")
    return path
